/** @type {import('tailwindcss').Config} */
// Import the shared config (adjust path if necessary, though package name should work)
import sharedConfig from "@repo/tailwind-config/tailwind-config.js";

export default {
  // Use presets to inherit the shared configuration
  presets: [sharedConfig],
  // Keep the app-specific content path generated by Astro
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  // You can add app-specific theme extensions or plugins here if needed
  theme: {
    extend: {},
  },
  plugins: [],
};
