/** @type {import('tailwindcss').Config} */
// Import the shared config (adjust path if necessary, though package name should work)
import sharedConfig from "@repo/tailwind-config/tailwind-config.js";

export default {
  // Use presets to inherit the shared configuration
  presets: [sharedConfig],
  // Keep the app-specific content path generated by Astro
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  // You can add app-specific theme extensions or plugins here if needed
  theme: {
    extend: {
      colors: {
        ultramarine50: "#e7f1ff",
        ultramarine100: "#d4e4ff",
        ultramarine200: "#b1cdff",
        ultramarine300: "#83aaff",
        ultramarine400: "#5278ff",
        ultramarine500: "#2b46ff",
        ultramarine600: "#0711ff",
        ultramarine700: "#0009ff",
        ultramarine800: "#020bd1",
        ultramarine900: "#0d17a0",
        ultramarine950: "#080c5e",
      },
    },
  },
  plugins: [],
};
